# config.yml generated for RealTime_1.16.5-0
# https://github.com/bssman89/RealTime/wiki/Configuration

config-autosave: true
config-autosave-period: 24000
weather-api-key: ""
weather-fetch-period: 1200

worlds:
  world: default

settings:
  default:
    sync-time: true
    time-zero: "1-01-01T00:00:00"
    time-offset: 0
    time-speed: 1.0
    sync-weather: false
    weather-city: ""
