main: me.bizroomba.realtime.RealTimePlugin
name: RealTime
version: "1.16.5-0"
api-version: "1.16"
authors:
  - Cynadyde
  - Biz_Roomba
description: >
  Sync world time and weather to real life.
website: https://github.com/bssman89/RealTime/wiki
commands:
  realtime:
    usage: ยง6/realtime
    description: shows plugin info and a list of sub-commands
permissions:
  realtime.*:
    description: grants access to all plugin abilities
    default: op
    children:
      realtime.admin: true
      realtime.mod: true
  realtime.admin:
    description: grants ability to modify and reload the config
    default: false
  realtime.mod:
    description: grants ability to sync and forget worlds
    default: false
